# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linux
spec:
  serviceName: linux
  replicas: 5
  selector:
    matchLabels:
      app: linux
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
        - name: linux-11
          image: registry.cn-beijing.aliyuncs.com/king019/linux:jdk11
---
apiVersion: v1
kind: Service
metadata:
  name: linux
spec:
  #  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      #    nodePort: 30001
      protocol: TCP
  selector:
    app: linux