apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:master
          imagePullPolicy: IfNotPresent
          ports:
            - name: p9091
              containerPort: 9091
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
spec:
  ports:
    - name: p9091
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: pushgateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pushgateway
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: pushgateway.k8s.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: pushgateway
                port:
                  number: 9091
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pushgateway-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pushgateway
            image: docker:5000/king019/alpine:pushgateway_delete
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sh /delete.sh
          restartPolicy: OnFailure
