kind: pipeline
name: build

steps:
  - name: buildDocker
    image: registry.cn-beijing.aliyuncs.com/king019/alpine:docker
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=2@rep=true@push=true"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./docker_true.sh
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /opt/soft/docker/data/jenkins/jkwk/config.json