kind: pipeline
name: build

steps:
  - name: build
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - chmod -R 777 /drone/src
      - which docker
      - docker version
      - docker info
      - source /etc/profile;java -version
      - mvn clean compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=false@local=true@in=alpine,centos,fedora,openeuler,rhel,linux,nacos"
      - chmod -R 777 /drone/src
      - sh ./target/local_region/platform/noSuffix_false.sh
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /opt/soft/docker/data/jenkins/jkwk/config.json