# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dubbo-nacos-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-dubbo-nacos-consumer
  template:
    metadata:
      labels:
        app: k8s-dubbo-nacos-consumer
    spec:
      containers:
        - name: k8s-dubbo-nacos-consumer
          image: docker:5000/king019/sshm_cloud_alibaba_nacos_rpc_registry_dubbo_consumer
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: dubbo
              containerPort: 20880
              protocol: TCP
          env:
            - name: server.port
              value: "8080"
            - name: dubbo.protocols.dubbo.port
              value: "20880"
            - name: dubbo.protocol.port
              value: "20880"
            - name: 'management.prometheus.metrics.export.pushgateway.groupingKey.instance'
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP


# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dubbo-nacos-consumer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8s-dubbo-nacos-consumer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  k8s-dubbo-nacos-consumer
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: nacos-dubbo-consumer.k8s.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8s-dubbo-nacos-consumer
                port:
                  number: 8080