# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dubbo-nacos-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-dubbo-nacos-server
  template:
    metadata:
      labels:
        app: k8s-dubbo-nacos-server
    spec:
      containers:
        - name: k8s-dubbo-nacos-server
          image: docker:5000/king019/sshm_cloud_alibaba_nacos_rpc_registry_dubbo_server
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: dubbo
              containerPort: 20880
              protocol: TCP
          env:
            - name: server.port
              value: "8080"
            - name: dubbo.protocols.dubbo.port
              value: "20880"
            - name: dubbo.protocol.port
              value: "20880"
            - name: 'management.prometheus.metrics.export.pushgateway.groupingKey.instance'
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP

# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dubbo-nacos-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8s-dubbo-nacos-server