# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: docker:5000/king019/sshm_cloud_alibaba_nacos_admin_server
          imagePullPolicy: Always
          ports:
            - containerPort: 8980
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP

# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - port: 8980
      targetPort: 8980
      protocol: TCP
  selector:
    app: admin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: admin.k8s.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin
                port:
                  number: 8980