# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-config
  template:
    metadata:
      labels:
        app: nacos-config
    spec:
      containers:
        - name: nacos-config
          image: docker:5000/king019/sshm_cloud_alibaba_config
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 20
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP

# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-config
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: nacos-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos-config
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: nacos-config.k8s.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nacos-config
                port:
                  number: 8080