# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaf-zk
  template:
    metadata:
      labels:
        app: kaf-zk
    spec:
      containers:
        - name: kaf-zk
          image: zookeeper:3.7
#          imagePullPolicy: Always
          ports:
            - name: tcp2181
              containerPort: 2181
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kaf-zk
spec:
  type: NodePort
  ports:
    - name: tcp2181
      port: 2181
      targetPort: 2181
      nodePort: 2181
      protocol: TCP
  selector:
    app: kaf-zk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: fogsyio/kafka:2.2.0
#          imagePullPolicy: Always
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: '9092'
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 'kafka'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'kaf-zk:2181'
          ports:
            - name: tcp9092
              containerPort: 9092
              protocol: TCP
        - name: kafka-manager
#          imagePullPolicy: Always
          image: scjtqs/kafka-manager
          env:
            - name: ZK_HOSTS
              value: 'kaf-zk:2181'
            - name: APPLICATION_SECRET
              value: '111111'
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP

# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  ports:
    - name: mq-console
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: mq-9092
      port: 9092
      targetPort: 9092
      nodePort: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kafka.k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka
                port:
                  number: 9000