kind: Pod
apiVersion: v1
metadata:
  name: minio-pod
  namespace: minio
spec:
  containers:
  - name: minio-pod
    image:  nginx
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false
