# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
    spec:
      containers:
        - name: rocketmq
          image: registry.cn-beijing.aliyuncs.com/king019/rocketmq
#          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: ' ${JAVA_OPT} -Xms512m -Xmx512m -Xmn128m -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=32m '
          ports:
            - name: tcp10911
              containerPort: 10911
              protocol: TCP
            - name: tcp9876
              containerPort: 9876
              protocol: TCP
        - name: mq-console
          imagePullPolicy: Always
#          image: registry.cn-beijing.aliyuncs.com/king019/rocketmq:console
          image: registry.cn-beijing.aliyuncs.com/king019/rocketmq:dashboard
          env:
            - name: JAVA_OPTS
              value: ' -Xms32m -Xmx32m -Xmn16m -Drocketmq.namesrv.addr=127.0.0.1:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false '
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq
spec:
  type: NodePort
  ports:
    - name: mq-console
      port: 8080
      targetPort: 8080
      #    nodePort: 8080
      protocol: TCP
    - name: mq-10911
      port: 10911
      targetPort: 10911
      nodePort: 10911
      protocol: TCP
    - name: mq-9876
      port: 9876
      targetPort: 9876
      nodePort: 9876
      protocol: TCP
  selector:
    app: rocketmq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocketmq-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rocketmq.k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rocketmq
                port:
                  number: 8080