# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
        - name: linux
          image: registry.cn-beijing.aliyuncs.com/king019/linux
          command: [ 'sh', '-c', "sleep 10" ]
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ 'sh', '-c', "echo 'waiting for myservice'" ]
        - name: init-mydb
          image: busybox:1.28
          command: [ 'sh', '-c', "echo 'waiting for mydb'" ]
---
apiVersion: v1
kind: Service
metadata:
  name: linux
spec:
  #  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      #    nodePort: 30001
      protocol: TCP
  selector:
    app: linux