# webapp-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
        - name: sentinel
          image: docker:5000/king019/sentinel:dashbord
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


# webapp-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  ports:
    - port: 9930
      targetPort: 8080
      protocol: TCP
  selector:
    app: sentinel
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: sentinel.k8s.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: sentinel
                port:
                  number: 9930