v1apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /nfs-share
    server: 172.17.0.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi # 注意这里的值小于等于 PV 的值
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      volumes:
          - name: host-pvc-vol
            persistentVolumeClaim:
              claimName: myclaim
      containers:
        - name: apollo-config
          image: registry.cn-beijing.aliyuncs.com/king019/alpine
          volumeMounts:
              - name: host-pvc-vol
                mountPath: /opt/soft/