name: host-10m-pv
  名字，见名知意，基于host的10m的pv
storageClassName: host-test
  存储class，进行分类，根据具体业务即可
  - ReadWriteOnce
    读写策略，完整如下：
    ReadWriteOnce：存储卷可读可写，但只能被一个节点上的Pod挂载。
    ReadOnlyMany：存储卷只读不可写，可以被任意节点上的Pod多次挂载。
    ReadWriteMany：存储卷可读可写，也可以被任意节点上的Pod多次挂载。
    这里是本地磁盘，自然是只能被一个节点上的POD挂载
storage: 10Mi
  大小10MB，但这里使用的是国际标准，不同于我们用的KB（1024 byte）,MB(1024*1024 byte)，一定不要写错
path: /tmp/host-10m-pv/
  要挂载的本地磁盘目录，没有的话需要手动创建该目录

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-5m-pvc

spec:
  storageClassName: host-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: host-pvc-pod

spec:
  volumes:
    - name: host-pvc-vol
      persistentVolumeClaim:
        claimName: host-5m-pvc

  containers:
    - name: ngx-pvc-pod
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: host-pvc-vol
          mountPath: /tmp
