kind: pipeline
name: build

steps:
  - name: buildLocal
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=true@ex=centos"
      - pwd;ls
      - sh ./target/local_region/noSuffix_false.sh

  - name: buildAliyunBeijing
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./aliyun_beijing_true.sh
  - name: buildAliyunShangHai
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./aliyun_shanghai_true.sh
  - name: buildAliyunHuHeHaoTe
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./aliyun_huhehaote_true.sh
  - name: buildAliyun_shenzhen
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./aliyun_shenzhen_true.sh
  - name: buildTenBeijing
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    #    detach: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./tenyun_beijing_true.sh

  - name: buildDocker
    image: registry.cn-beijing.aliyuncs.com/king019/docker:build
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
      - name: docker
        path: /bin/docker
      - name: sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker/config.json
    commands:
      - chmod -R 777 /bin
      - which docker
      - docker version
      - source /etc/profile;java -version
      #      - mvn clean
      - mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/drone/src@thread=1@rep=true@push=true@local=false@ex=centos"
      - pwd;ls
      - chmod -R 777 .
      - cd ./target
      - sh ./docker_true.sh
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2
  - name: docker
    host:
      path: /usr/bin/docker
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /opt/soft/docker/data/jenkins/jkwk/config.json