name: docker_info

on:
  push:
    branches: [ "master" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          arch: armv8
          distro: ubuntu-20.04
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }};
          sudo sed -i "s/{/{\"experimental\":true,/g"  /etc/docker/daemon.json;
          cat /etc/docker/daemon.json;
          sudo service docker restart;
      - name: docker info
        run: docker info
