name: docker_docker

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See https://github.com/actions/setup-java
          java-version: '17'
      - name: docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: chche
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }};java -version
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }};
          java -version;
          mvn -version;
          ls /home/runner/work/docker/docker;
      - name: docker info
        run: docker info
      - name: maven
        run: pwd;
          cd /home/runner/work/docker/docker;
          ls /home/runner/work/docker/docker;
          mvn compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsBuildShell" -Dexec.args="ws=/home/runner/work/docker/docker@thread=20@rep=false@push=true@origin=false@mix=true@suf=true";
      - name: build_docker
        run: pwd;
          cd /home/runner/work/docker/docker;
          ls /home/runner/work/docker/docker;
          cd ./target;chmod -R 777 .;
          ls;
          bash ./docker_true.sh;
