name: docker_aliyun_qd_upload_amd64.yml

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See https://github.com/actions/setup-java
          java-version: '17'
      - name: chche
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven
      - name: aliyun_qingdao
        uses: docker/login-action@v1
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: maven
        run: pwd;
          cd /home/runner/work/docker/docker;
          ls /home/runner/work/docker/docker;
          mvn clean compile exec:java -Dexec.mainClass="com.k.docker.jenkins.JenkinsTransBuildSplitShell" -Dexec.args="arm=false@maxStep=20"
      - name: build_aliyun_qingdao_upload
        run: pwd;
          cd ./;chmod -R 777 .;
          pwd;
          ls ./;
          bash ./target/aliyun_qingdao.sh;
